version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-ocr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10azt8hpv229p"
s3_prefix = "aws-sam-ocr"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
